
stages:
  - build

build_android:
  stage: build
  image: ubuntu:22.04
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .gradle/
      - android/.gradle/
      - android-sdk/
  before_script:
    - apt-get update && apt-get install -y openjdk-17-jdk unzip wget curl
    # Install Node.js 18 (required for React Native 0.79.5)
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - export PATH=$PATH:$JAVA_HOME/bin
    # Install Android SDK
    - mkdir -p android-sdk
    - cd android-sdk
    - wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
    - unzip -q commandlinetools-linux-11076708_latest.zip
    - mkdir -p cmdline-tools/latest
    - mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
    - export ANDROID_HOME=$PWD
    - export ANDROID_SDK_ROOT=$PWD
    - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
    - yes | sdkmanager --licenses || true
    - sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
    - cd ..
    # Install Node dependencies
    - npm install
  script:
    - cd android
    - chmod +x ./gradlew
    - ./gradlew assembleDebug --stacktrace --no-daemon
  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/app-debug.apk
    expire_in: 7 days
  timeout: 60m
